### ISSUE TITLE
Anyway to make the bookmarks bar show?

### ISSUE THREAD

**Issue by Dobbie03** [akshat46/FlyingFox#10]
I really love this configuration.  Just spot on work.

I'm wondering if there is a way to make the bookmarks bar permanently display?

**Comment by akshat46** [comment]
Sorry about the late response. Do you mean the tst sidebar or the bookmarks bar that replaces sidebar when `ctrl+b` is pressed?  
As of right now, its pretty much impossible to get a separate bookmarks bar that is static (and doesn't show up only when hovered) while also having a hoverable tst sidebar. Mainly because of [mozilla's decision to not have multiple sidebars at a time](https://bugzilla.mozilla.org/show_bug.cgi?id=1328776) and so currently tst just replaces the contents of bookmarks sidebar.
I have fixed the broken bookmarks sidebar and added a few options for a permanent sidebar. Which will result in both tst, and bookmarks being permanent. [Take a look](https://github.com/akshat46/FlyingFox/tree/master/chrome).
You can also try the extension that lets you [add bookmarks subpanel to tst](https://github.com/akshat46/FlyingFox/tree/master/chrome). I am not sure how it will behave with my configs though.
