### ISSUE TITLE
Pinned Tabs acting weird

### ISSUE THREAD

**Issue by alzedd** [akshat46/FlyingFox#20]
So, a couple of things.

* there is a line that strikes through pinned tabs
* selected pinned tabs goes under the reserved row and all the way to the right

here are a couple of images for reference. 
![Schermata 2020-12-04 alle 12 14 24](https://user-images.githubusercontent.com/29459468/101157370-4f2fef80-362a-11eb-9c5c-84551548a402.png)
![Schermata 2020-12-04 alle 12 14 29](https://user-images.githubusercontent.com/29459468/101157376-51924980-362a-11eb-9ebe-a1cdaeccc826.png)

**Comment by akshat46** [comment]
Yes the strike is a known bug that I thought I fixed already. Will take a look once I'm free. 

How would you expect the pinned tab to work otherwise if not move all the way to the right? Intention behind moving it to right was so that they show up properly in the userChrome-hover sidebar but if there's any other way you think might be better then I'm open to ideas. Should probably add separate behavior for static sudebars.

**Comment by alzedd** [comment]
Sorry, came with a problen and didn't bother to suggest a solution. 

You're right, you probably should separate the behaviours on static and hover sidebars.
On hover it could work like this, on static maybe it's better to just highlight the active tab and leave it with the others on the top of the sidebar.
