### ISSUE TITLE
Enhancements for  Children Tabs

### ISSUE THREAD

**Issue by piyush-das** [akshat46/FlyingFox#26]
Hi,

It seems that text on certain children is visible in certain cases while hovering.
![Screenshot from 2021-01-03 09-45-20](https://user-images.githubusercontent.com/68941107/103471627-7d7b2900-4da8-11eb-800c-9cf0c8517907.png)

Thanks

**Comment by piyush-das** [comment]
The Issue seems to be resolved with a firefox update. Thanks

**Comment by akshat46** [comment]
The tst css doesn't handle tree-structures as of right now. If you import treestyletab/config.json from the repo, this shouldn't happen because that configuration disables tree functionality of tst. You can also do that yourself by disabling `autoAttach` and `syncParentTabAndOpenerTab`. Original comment from [treestyletab discussion](https://github.com/piroor/treestyletab/issues/1544#issuecomment-522902490):

> Go to Tools > Add-Ons > Find "Tree Style Tab" and click on the three dots "..." next to its entry to select "Preferences" > Scroll all the way down to an expandable menu named "All Configs" > Click on the small black triangle to expand the menu if it isn't already > Uncheck the checkboxes autoAttach and syncParentTabAndOpenerTab.

**Comment by akshat46** [comment]
This should be fixed with the new update since Flyingfox now (attempts to) theme branching in TST for both, hover and static sidebars. It works perfectly with static but hover may be off-putting at times if the branch is very deep. 

As per the main bug of text being visible, there's now a `--hover-text-spacing` variable at the top of TST css whose value can be increased to hide the text properly.  [Read about it more in wiki.](https://github.com/akshat46/FlyingFox/wiki/3.-Sidebar#sidebar-variables)
