### ISSUE TITLE
any plans on porting this to vivaldi?

### ISSUE THREAD

**Issue by KraXen72** [akshat46/FlyingFox#27]
looks clean any plans on porting it to vivaldi? vivaldi has a built in feature where you can select a custom css file but it obviously has to have the respective classes etc. 

for an example see this: https://github.com/KraXen72/rosebox/tree/master/vivaldi#custom-css

**Comment by akshat46** [comment]
That looks great! Didn't know vivaldi supported custom CSS too but I probably won't be working on it any time soon. Mostly because I don't personally use vivaldi so it will be very difficult to maintain the port. Besides, my main focus for this project has been finishing [v0.1](https://github.com/akshat46/FlyingFox/tree/v0.1) for last few weeks and I am still ways from being done.

**Comment by KraXen72** [comment]
alright, if you finish v0.1, i might look into the main elements FlyingFox changes or like the main design changes it does and port it to vivaldi
