### ISSUE TITLE
Search engines toolbar does not appear at the bootom of search-bar

### ISSUE THREAD

**Issue by axonasif** [akshat46/FlyingFox#72]
**Describe the bug**
Equal to the title of this issue.
Edit: The search-engines toolbar is basically gone on behalf of the theme.
 
**To Reproduce**
1. Open location bar (aka search bar).
2. Notice what's in the bottom of it.

**Screenshots**
![image](https://user-images.githubusercontent.com/39482679/118074124-237e1600-b3cf-11eb-98c4-401cf4bc0e10.png)

 **Firefox Version:**
Firefox 87 Linux.

**Comment by akshat46** [comment]
Yes, that was intentional because I personally never used it since ddg bangs do everything and more. I guess that's the "opinionated" part of this theme. 

You can bring it back by commenting out [line 112 in `chrome/urlbar.css`](https://github.com/akshat46/FlyingFox/blob/master/chrome/urlbar/urlbar.css#L112). Doesn't seem to break any styles at first glance.

**Comment by axonasif** [comment]
> ddg bangs
Ah, this seems cool ;) @akshat46
And there seems to be extensions too.
I'm not looking to bring back that bar any longer :laughing: 
Using `alt` keys to change search engine was a PITA.
Thanks!
