### ISSUE TITLE
Small Issues

### ISSUE THREAD

**Issue by UnPossible-Me** [akshat46/FlyingFox#80]
![tempsnip](https://user-images.githubusercontent.com/71452014/120116301-2b96cd80-c1a5-11eb-814f-27c52f469090.png)

Hello,
As seen in the photo:  

1. The button and part above the search bar has... sprung into existence, it wasn't there when I installed it, but I somehow messed something up and don't know which file, or what to edit.

2. As seen in the drop-down menu, the right side it getting cutoff, how can I fix that?

3. In the images I've seen, the icons have a halo/glowing effect to them, I've managed to disable the mask and bring back regular icons reading though the issues, but I how I apply iridescent ones?

**Comment by akshat46** [comment]
1. The first part is menu bar. It's usually toggled with `alt`. Springing to that position is a known issue that I ignored last time I saw it because I've been lazy. 
2. Not sure. Looks like you are using v89 which unfortunately isn't supported. I will have some free time in a few weeks and I am hoping to get this project up to speed but till then it's kinda dead considering v89 released today. :no_mouth: 
3. What do you mean by "iridescent ones"? Are you talking about any specific icons either tst tan icons or navbar icons?

**Comment by UnPossible-Me** [comment]
I thought about using `alt`, but that just selects "files" and deselects it, no change to the UI unfortunately. 

Indeed, I am using FF 89, that's a shame, I didn't expect this to break, but that's okay. Take your time with it. :)

![tempCapture](https://user-images.githubusercontent.com/71452014/120133747-59523580-c1ea-11eb-834e-da04a4d080c7.PNG)
I suppose my wording was incorrect, that is what I mean. 
If you could what does hntp mean, DDG brought up nothing, and I could understand much from the ReadMe in the other_configs folder either.

**Comment by akshat46** [comment]
[This](https://support.mozilla.org/en-US/kb/restore-menu-bar-firefox?redirectslug=what-happened-to-the-file-edit-and-view-menus&redirectlocale=en-US) seems relevant to menu bar. Otherwise I am not sure how it'll be fixed. The css doesn't do anything to menu bar so it must be something with Firefox itself. 

Oh that's from old css. You'll have to change things in either treestyletab/config.css or config-hover.css depending on which you want to use. I'm on phone right now but I can tell a bit more detail in few hours. 

Hntp is [humble new tap page](https://addons.mozilla.org/en-US/firefox/addon/humble-new-tab/). Also from old configs.

**Comment by UnPossible-Me** [comment]
Many thanks for the help!
Yep it turned out to be a FF issue and your method worked perfectly. 

As for the others, I start to see now, I'll try experimenting a bit.
